name: AegisCI Build & Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Unit Tests & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          check-latest: true

      - name: Verify Dependencies
        run: go mod verify

      - name: Run Unit Tests with Coverage
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Build Binary
        run: go build -v -o bin/aegisci ./cmd/aegisci
